---
- name: Create directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - "/var/lib/kubelet/pki"
    - "/opt/bootstrap-scripts"
    - "/opt/templates"
    - "/run/systemd/resolve"
    - "/etc/kubernetes/manifests"

- name: Download cert binary files
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop: 
    '{{ downloads }}'

- name: Copy kubelet config/service files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "640"
  loop:
    - { src: "config/kubelet-config.yaml.j2", dest: "/opt/templates/" }
    - { src: "config/kubelet.service.j2", dest: "/opt/templates/" }
    - { src: "config/sysctl.conf", dest: "/etc/" }

- name: Adding configuration, startup and service files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest + item.src.split('/')[-1].split('.')[0] + '.' + item.src.split('/')[-1].split('.')[1] }}"
    owner: root
    mode: "0750" 
  loop:
    - { src: "bootstrap/bootstrap-kubelet.sh.j2", dest: "/opt/bootstrap-scripts/" }
    - { src: "bootstrap/generate-certs-and-configs.sh.j2", dest: "/opt/bootstrap-scripts/" }

- name: Remove swap from fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^#? ?(.*swap.*$)'
    replace: '# \1'

- name: Set the KUBECONFIG variable
  copy:
    dest: /etc/profile.d/kubeconfig.sh
    content: "export KUBECONFIG=/var/lib/kubelet/kubeconfig"
  when: node_role == "worker"

- name: Create symbolic links
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "/etc/resolv.conf", dest: "/run/systemd/resolve/resolv.conf" }
