---
- name: Converge
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - role: centos
    - role: install_cloudinit
    - role: containerd
      cntlr_cidr: "10.1.0.0/24"
      cri_version: "v1.21.0"
      runc_version: "v1.0.0-rc91"
      containerd_version: "1.3.6"
      cni_version: "0.3.1"
      cni_plugin_version: "v0.8.6"
    - role: kubelet
      # Expected to be kubernetes/<version>/<necessary binaries>
      node_role: "worker"
      cert_version: "1.4.1"
      k8s_version: "v1.20.2"
    - role: download_untar
      download:
        - {url: "https://github.com/luishmg/python-jinja-renderer/archive/refs/tags/v2.4.tar.gz", dest: "/opt/pytools/"}
  post_tasks:
    - name: Install jinja2 for Python 3, using the pip3 executable
      pip:
        name: jinja2
        executable: pip3
    - name: Install pyrender tool
      pip:
        name: /opt/pytools/python-jinja-renderer-2.4
        executable: pip3
