---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    memory: 512
    cpus: 2
platforms:
  - name: test-role-centos7
    box: centos/7
provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint:
    name: ansible-lint
verifier:
  name: inspec
